import "animate.css";
import "antd/dist/reset.css";
import "@/assets/styles/globalStyle.scss";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import AntdComponentsWrapper from "@/layouts/components/AntdComponentsWrapper";
import DefaultLayout from "@/layouts/default";

export const metadata: Metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AntdComponentsWrapper>
          <DefaultLayout>{children}</DefaultLayout>
        </AntdComponentsWrapper>
      </body>
    </html>
  );
}
